# Generated by Django 5.0.6 on 2024-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0002_remove_company_email_alter_company_user_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
